# Generated by Django 2.2.3 on 2019-09-22 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback_home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Id_Number', models.IntegerField(primary_key=True, serialize=False)),
                ('Student_Name', models.CharField(max_length=100)),
                ('Batch_year', models.CharField(max_length=100)),
                ('Branch', models.CharField(max_length=100)),
                ('Email_Id', models.EmailField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
